name: Haven
version: '${version}'
main: net.haven.Haven
api-version: '1.16'
authors: [Ilya Bush]
description: A flexible plugin for setting the spawnpoint!
website: https://www.youtube.com/@IlyaBush-001
commands:
  setspawn:
    description: Set SpawnPoint
    usage: /setspawn
    permission: haven.command.setspawn
  spawn:
    description: Teleport to Spawn
    usage: /spawn
    permission: haven.command.spawn
  delspawn:
    description: Delete SpawnPoint
    usage: /delspawn
    permission: haven.command.deletespawn
  hvreload:
    description: Reload plugin
    usage: /hvreload
    permission: haven.command.hvreload
